### ISSUE TITLE
Prevent minimizing tag names

### ISSUE THREAD

**Issue by Lee182** [izolate/html2pug#33]
```html
    <Page>
        <ActionBar>
            <GridLayout width="100%" columns="auto, *">
                <Label text="MENU" @tap="$refs.drawer.nativeView.showDrawer()" col="0"/>
                <Label class="title" text="Welcome to NativeScript-Vue!"  col="1"/>
            </GridLayout>
        </ActionBar>

        <RadSideDrawer ref="drawer">
            <StackLayout ~drawerContent backgroundColor="#ffffff">
                <Label class="drawer-header" text="Drawer"/>

                <Label class="drawer-item" text="Item 1"/>
                <Label class="drawer-item" text="Item 2"/>
                <Label class="drawer-item" text="Item 3"/>
            </StackLayout>

            <GridLayout ~mainContent columns="*" rows="*">
                <Label class="message" :text="msg" col="0" row="0"/>
            </GridLayout>
        </RadSideDrawer>
    </Page>
```
will output
```pug
page
  actionbar
    gridlayout(width='100%', columns='auto, *')
      label(text='MENU', @tap='$refs.drawer.nativeView.showDrawer()', col='0')
        label.title(text='Welcome to NativeScript-Vue!', col='1')
  radsidedrawer(ref='drawer')
    stacklayout(~drawercontent='', backgroundcolor='#ffffff')
      label.drawer-header(text='Drawer')
        label.drawer-item(text='Item 1')
          label.drawer-item(text='Item 2')
            label.drawer-item(text='Item 3')
    gridlayout(~maincontent='', columns='*', rows='*')
      label.message(:text='msg', col='0', row='0')

```
Errors to me
1. Tag names have been converted to lower case they should remain the same case as input.
2. Label inline tag for some reason has ended up indented.

**Comment by izolate** [comment]
Hi @Lee182,

I appreciate you reporting this, but it seems your errors are due to you attempting to transform XML to Pug. This library doesn't support XML, only HTML.

#### 1. Tag names have been converted to lower case they should remain the same case as input.
Ideally, yes. However HTML, unlike XML/XHTML, is **case insensitive** so `<ActionBar>` and `<actionbar>` are the same element as per the HTML specification. 

Case sensitivity is a feature I'd like to add but the maintainers of the HTML parsing library in use (`parse5`) have [expressed their reluctance](https://github.com/inikulin/parse5/issues/223#issuecomment-344100118) to deviate from the specification, so I'm afraid this won't be possible any time soon.

#### 2. Label inline tag for some reason has ended up indented.
Again, the omission of the closing tags on the `<Label>` element is valid XML but _invalid_ HTML. The HTML specification states:

> [Tag omission in text/html: Neither tag is omissible](https://www.w3.org/TR/html/sec-forms.html#the-label-element)

You can add the closing tags to correct the indent error.

Hope this helped.
